import React,{useEffect,useState}from'react';import{Pressable,ScrollView,StyleSheet,Text,View}from'react-native';import{useTheme}from'../theme/ThemeProvider';import{Bell,ShieldCheck,UserCircle,ChartLine}from'phosphor-react-native';import{pinStatus,supabase}from'../services/supabase';import{GOLD}from'../theme/theme';
export function SimpleScreen({title,icon:Icon,children}:any){const{colors}=useTheme();return<ScrollView style={{backgroundColor:colors.bg}} contentContainerStyle={styles.wrap}><View style={styles.top}><View style={styles.icon}><Icon color="#0F0E0B" size={22} weight="bold"/></View><Text style={[styles.title,{color:colors.text}]}>{title}</Text></View>{children}</ScrollView>}
export function SecurityScreen(){const[status,setStatus]=useState<any>();useEffect(()=>{pinStatus().then(setStatus)},[]);const{colors}=useTheme();return<SimpleScreen title="Security" icon={ShieldCheck}><Card colors={colors}><Text style={{color:colors.text,fontWeight:'900'}}>PIN lock</Text><Text style={{color:colors.muted,marginTop:5}}>{status?.pin_enabled?'Enabled — your existing RainX PIN remains active.':'Not enabled'}</Text></Card><Card colors={colors}><Text style={{color:colors.text,fontWeight:'900'}}>Biometric unlock</Text><Text style={{color:colors.muted,marginTop:5}}>Use the device biometric system when enabled.</Text></Card></SimpleScreen>}
export function NotificationsScreen(){const{colors}=useTheme();return<SimpleScreen title="Notifications" icon={Bell}>{['Trading alerts','Community activity','Raina AI','Security alerts','News'].map(x=><Card key={x} colors={colors}><View style={styles.between}><Text style={{color:colors.text,fontWeight:'800'}}>{x}</Text><View style={styles.dot}/></View></Card>)}</SimpleScreen>}
export function SettingsScreen(){const{colors}=useTheme();return<SimpleScreen title="Settings" icon={ChartLine}>{['Account','Appearance','Language','Privacy','Data & security','About RainX'].map(x=><Card key={x} colors={colors}><Text style={{color:colors.text,fontWeight:'800'}}>{x}</Text></Card>)}</SimpleScreen>}
export function ProfileScreen(){const{colors}=useTheme();const[p,setP]=useState<any>();useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(data.session){const{data:p}=await supabase.from('profiles').select('*').eq('id',data.session.user.id).maybeSingle();setP(p)}})},[]);return<SimpleScreen title="Profile" icon={UserCircle}><Card colors={colors}><Text style={{color:colors.text,fontSize:20,fontWeight:'900'}}>{p?.display_name||'RainX Trader'}</Text><Text style={{color:colors.muted,marginTop:4}}>@{p?.username||'trader'}</Text></Card></SimpleScreen>}
export function CreatorScreen(){const{colors}=useTheme();return<SimpleScreen title="Creator dashboard" icon={ChartLine}><Card colors={colors}><Text style={{color:colors.text,fontWeight:'900'}}>Your Space Coins</Text><Text style={{color:colors.muted,marginTop:5}}>Liquidity, market analytics, holders and token management.</Text></Card></SimpleScreen>}
export function RewardsScreen(){const{colors}=useTheme();return<SimpleScreen title="Rewards" icon={ChartLine}><Card colors={colors}><Text style={{color:colors.text,fontSize:26,fontWeight:'900'}}>GHS 0.00</Text><Text style={{color:colors.muted,marginTop:5}}>Available rewards</Text></Card></SimpleScreen>}
function Card({colors,children}:any){return<View style={[styles.card,{backgroundColor:colors.card,borderColor:colors.border}]}>{children}</View>};const styles=StyleSheet.create({wrap:{padding:18,paddingBottom:40},top:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},icon:{width:45,height:45,borderRadius:14,backgroundColor:GOLD,alignItems:'center',justifyContent:'center'},title:{fontSize:25,fontWeight:'900'},card:{borderWidth:1,borderRadius:18,padding:16,marginBottom:9},between:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},dot:{width:9,height:9,borderRadius:5,backgroundColor:'#1A7A50'}});
